### ISSUE TITLE
컨포넌트 backdrop static 옵션 구현 요청

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#11]
@kieregh  모달을 제외하고 backdrop을 출력하는 컨포넌트 전체에 포함되는 옵션입니다.

backdrop false 와 함께 static 옵션이 필요합니다.

해당 옵션은 백드럽을 탭핑했을때에도 컨포넌트를 비활성 시키지 않는 옵션인데요.
주로 popup 컴포넌드로 경고대화창 등으로 활용할 때 사용됩니다. 
### 데모

https://jsfiddle.net/gitaek/1wu2p4L1/
### 참고 -bs의 modal의 static 옵션과 기능이 유사

http://getbootstrap.com/javascript/#modals-options

**Comment by kieregh** [comment]
아래와 같이 추가했습니다.
https://github.com/kimsQ/rc/commit/25594f5792e01620a8fe25a3d9987f98db81a891
