### ISSUE TITLE
데스크탑 click 이벤트 이슈 관련 

### ISSUE THREAD

**Issue by kieregh** [kimsQ/rc#15]
관련하여 수정작업 후 아래와 같이 커밋을 했습니다. 
https://github.com/kimsQ/rc/commit/f3826e12ab97c9a860de05e6ec8f81377ea546f5
그런데...커밋 페이제이 나타나지를 않네요....

위 수정된 소스가 적용된 샘플은 아래에서 확인 가능합니다
1. push 테스트 : http://www.withconsumer.net/rc-test/control/duck.php 
2. segment 테스트 : http://www.withconsumer.net/rc-test/control/affix.html

위 커밋내용에서도 말했지만....tap 이벤트를 사용해서 a 이벤트가 안되는 것은 아니었음을 
다시 한 번 말씀 드립니다.

이상입니다.

**Comment by gitaeks** [comment]
본, 커밋 이후,  스마트폰에서 form 입력이 안되고 있습니다.
https://jsfiddle.net/gitaek/ev7zsu4p/

RC는 only mobile에 주안점을 두고 있습니다. desktop 접근은 옵션사항임을 염두해 주시기 바랍니다.
touch와 click이 상충하는 경우가 있다면, touch기반으로 설계가 되어야 하며, 

그 모든상황을 포함하기 위해서 코드량이 늘어나고 성능이 저하되는 경우는 없어야 할 것 입니다.

**Comment by gitaeks** [comment]
아래 참고해 주세요.
http://ionicframework.com/docs/api/page/tap/

**Comment by kieregh** [comment]
아래 커밋으로 오류 수정하였습니다.
https://github.com/kimsQ/rc/commit/fe5188622bb2b740e9fb82f9929c76f78f22c2cb
