### ISSUE TITLE
extension-drawer  구조화 요청

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#19]
@kieregh 님, extension-drawer 구조화 요청 합니다.
자세한 내용은 아래를 참고해 주세요.
### 관련 문서

https://docs.google.com/document/d/16ebsalIj7CT4zfbc7EBJksmNoVQWITRYzbc6mdhHn2c/edit#heading=h.apd8daqonas0
### 기본 데모

https://jsfiddle.net/gitaek/8accod0z/

**Comment by kieregh** [comment]
아래와 같이 완료했습니다.
커밋 : https://github.com/kimsQ/rc/commit/2b17f75090e8713ec6ad68fd51923b504597c8e1
데모 : https://jsfiddle.net/kiere/jeb1c5vu/2/
