### ISSUE TITLE
action page의 start page의 이벤트(메소드) 적용 안됨

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#21]
action page 컴포넌트에서 이벤트(메소드)적용이 안되는 이슈
target page는 적용이되나 start page는 이벤트(메소드)적용이 안되는 현상
### 관련문서

[링크](https://docs.google.com/document/d/1OoTTziXL0DSsD8Ii5oc0kkF9sbbuZX6e4rsofE1JIVE/edit#heading=h.qw7kjznzbdcv)

**Comment by gitaeks** [comment]
위 상황은 아래 예제에서 재현해 볼수 있습니다. 
https://jsfiddle.net/gitaek/nepf6mgs/

**Comment by kieregh** [comment]
해당 target 에 이벤트를 트리거하는 것이 일관된 인터페이스 입니다.
즉, modal 처럼...오픈하는 대상 페이지가 target 입니다. 

스크립트를 아래와 같이 수정하면 됩니다.

```
$('#page-login').on('shown.rc.page', function() {
    $('#myFbutton').css('display', 'none');
})
$('#page-login').on('hidden.rc.page', function() {
    $('#myFbutton').css('display', 'block');
})
```
