### ISSUE TITLE
rc-control.js > scroll.js  미작동 

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#24]
Affix 데모를 만들고 있습니다. 미작동 이슈가 있습니다. 확인 요청합니다. 

데모 
https://jsfiddle.net/gitaek/fxrL6tr8/

**Comment by kieregh** [comment]
아래 이슈내용과 데모를 참조해주시기 바랍니다.
https://github.com/kimsQ/rc/issues/25

**Comment by kieregh** [comment]
아래와 사항 참조하셔서 Document 수정해주시기 바랍니다. 

### data-control 엘리먼트 마크업 이슈

   가. class="affix"
     이것은 동적으로 생성되는 것이기 때문에 최초 마크업에 포함시키면 안됩니다.

   나. data-offset
    - 이 값은 scroll 이 top 에서 어느정도 떨어졌을 때 affix 를 실행할 것인지 기준값입니다.
      이 값을 설정하지 않으면 기본값 10 으로 세팅됩니다.  
    - Document 에서는 이 값을 설정하지 않은 것으로 판단되는데요....이 값을 설정하지 않으면 
       기본값 10 이 적용되어 페이지 로드와 동시에 affix 가 실행됩니다. 아래 예제의 console 값을
       확인해보시기 바랍니다. 
       http://www.withconsumer.net/rc-test/control/affix-no-offset.html

### body 마크업 이슈

   rc.kimsq.com document 에서는 아래와 같은 마크업 구조인데요

```
   <div class="content">
         <div class="content-padded">
               <div data-control="scroll" data-type="affix"></div>
         </div>
   </div>    
```

   위 마크업에서 `<div class="content-padded">` 를 제거하면 정상 작동됩니다.

### Scroll 타겟 이슈

   .content 가 없는 경우 target 을 window 로 하면 되지만, content 가 있는 경우
   window 로 하면 작동되지 않습니다.  이 이유에 대해서는 잘 모르겠습니다.

   아래는 content 가 없는 bs 원본 affix 예제입니다.
   http://www.withconsumer.net/rc-test/control/affix-bs.html
   (적용된 bs-affix.js 를 보면 target 이 window 로 되어 있습니다.)

  content 가 있건 없건 타겟이 window 이면 작동되야 할 것 같은데...이상하네요... 
  content 엘리먼트와 scroll 작동의 연관성이 매우 밀접한 것으로 생각됩니다.

요컨대, 아래의 정상 예제를 참조하시어 document 수정해주시기 바랍니다.
http://www.withconsumer.net/rc-test/control/affix.html

이상입니다.

**Comment by gitaeks** [comment]
네.  잘 잘동는 것 확인했습니다. js관점에서는 잘되는 것 같습니다.  보여주는 부분에서 문제는 확인되었는데요.  css 수준에서 처리해야 할 것 같습니다.  처리되면 댓글 달겠습니다.

**Comment by gitaeks** [comment]
@kieregh affix 예제는 아래와 같이 개선하였습니다.
affix control  기본기능은 완성된것 같습니다. 

http://rc.kimsq.com/examples/controls/affix/content.html
