### ISSUE TITLE
photoswipe 익스텐션 구조화 요청 

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#27]
@kieregh , photoswipe 익스텐션 구조화 요청 합니다.
### 개요
- 익스텐션명 :  photoswipe
- 공식사이트 :  http://photoswipe.com/
- 저장소 : https://github.com/dimsemenov/photoswipe
### 기본예제
- [기본형-스크립트형](https://kimsq.github.io/rc/examples/extension/photoswipe/default.html)
- [링크목록형-마크업형](https://kimsq.github.io/rc/examples/extension/photoswipe/listOfLinks.html)

**Comment by gitaeks** [comment]
예제에 적용된 소스코드는 아래를 참고해 주세요.
https://github.com/kimsQ/rc/tree/gh-pages/examples/extension/photoswipe

**Comment by kieregh** [comment]
우선 아래와 같이 기본구조는 잡았습니다.
- 스크립트형
  http://jsfiddle.net/kiere/j91mtpmm/1/
- 링크목록/마크업형
  http://jsfiddle.net/kiere/b0v8urfn/2/

##. 전체 구조 요약
1. 바인딩 
- 아래 2 가지 방식 모두 pswp 마크업을 javascript 에서 동적으로 생성하도록 했습니다. 
- 아래 2 가지 방식 모두 data- 속성 값을 통해서 옵션 적용되도록 했습니다.
1. 바인딩 
   1) 마크업형 
   - gallery 단위로 data-extension="photoswipe" 으로 해서 바인딩을 했습니다. 
   
   2) 스크립트형
   - 이벤트 버튼에 data-toggle="photoswiper" 로 바인딩을 했습니다.  
2. 기본제공 옵션값 정리 요청
   - 예를 들어 예제 상으로 script 방식에서는 history : flase 로 하고 showAnimationDuration : 0 로 
     하는 등 기본 옵션값이 달라지는데요....이 것들에 대한 명확한 룰이 있어야 할 것 같습니다.
   - 작업/문서를 먼저 만들어놓고 나중에 수정하려니 번거로워서 미리 정하고 문서작업을 하려고 합니다.

이상입니다.

**Comment by gitaeks** [comment]
수고하셨습니다
history 와 showAnimationDuration 등의 옵션은 `링크목록형-마크업형` 예제가 일반적인것으로 판단되니 이를 기준으로 옵션 기본값을 설정해 주시면 될 것 같습니다.

**Comment by gitaeks** [comment]
### pswp 마크업 동적 생성 관련

본 마크업을 동적생성하여 간결한 적용이 가능한 장점이 있지만, 반면,  포토모달(pswp)의 커스텀이 불가능한 단점이 있는 것 같습니다.   pswp 마크업 동적생성여부를 옵션화 한후, 기본값을 동적생성으로 처리했으면 합니다.

특수한 경우( 포토모달의 구성상의 수정이 필요한 경우 ) pswp 마크업 동적생성 기능을 비활성 처리한 후,  커스텀된 포토모달(pswp) 직접 추가할 수 있으면 확장성에 도움이 될 것 같습니다.

### HTML In Slides

카드뉴스 형식 구현에 활용될 수 있는 기능으로 판단됩니다. 본 기능 또한 구조화 요청 합니다. 
- 예제 :  https://kimsq.github.io/rc/examples/extension/photoswipe/htmlInSlides.html
- 관련내용 : http://photoswipe.com/documentation/custom-html-in-slides.html

**Comment by kieregh** [comment]
추가 요청사항 적용해서 완료했습니다.

문서작성도 완료했으며 모든 예제도 업데이트했습니다.
