### ISSUE TITLE
push control 작동시  photoswipe  컨테이너 생성되는 오류

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#29]
@kieregh 아래 예제에서 탭을 몇번 방법 탭하다보면 push control 과 상관없는 photowipe 컨테이너가 생성되는 오류가 있습니다.

http://rc.kimsq.com/examples/tab-bar/index.html

![image](https://cloud.githubusercontent.com/assets/5070245/17201659/6a1bcdcc-54cb-11e6-84e2-e55ce42ca306.png)

**Comment by kieregh2** [comment]
본 이슈와 관련하여....프레임 자체에서 push 바인딩을 하는 것은 문제가 있어 보입니다.
push  이벤트가 발생하면 프레임안에서 설정된 바인딩이 작용하여 바인딩된 함수가 실행되는
현상입니다.

push  바인딩은 해당 페이지에서 하는 것으로 안내를 하고  push  메뉴얼에서 방법을 기재하는 것으로
하면 될 것으로 생각합니다.
