### ISSUE TITLE
모달 애니메이션 효과 

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#3]
@kieregh 모달 호출시  `data-animation="scale"` 의 옵션이 설정되었다면 모달의 컨테이너에  `data-animation`에 지정된 값이 모달 컨테이너의 클래스로 동적으로 지정되어야 하는데, 현재 관련 기능이 누락되어 있는 것 같습니다. 확인 요청 합니다.

```
<div class="modal scale">
    ...
</div>
```

자세한것은 아래를 참조해 주세요. 
[모달 애니메이션 효과 데모 및 소스코드](https://docs.google.com/document/d/1OoTTziXL0DSsD8Ii5oc0kkF9sbbuZX6e4rsofE1JIVE/edit#heading=h.argxq8z192kv)

**Comment by kieregh** [comment]
추가했습니다.

**Comment by gitaeks** [comment]
본 옵션은 추후 rb에서 동적으로 모달 컨테이너를 생성시킬때 사용하기 위한 옵션 입니다.

수동으로 모달 컨테이너를 생성하는 경우, 모달 컨테이너에 `scal` 클래스가 누락되어  최초모달 호출시에도 에니메이션을 적용할 수 있는데요.

추후 rb에서 동적으로 모달 컨테이너 생성시 본 옵션이 있으면 컨테이너 생성시에 동적으로 적용해 주세요.
