### ISSUE TITLE
toggle.js  제외 및 추가 요청

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#35]
@kieregh 님, `toggle.js` 내부에 `getBrowserCapabilities` 오류로 일단, `toggle.js` 를  `ratchet-plus.js`에서 제외 하였습니다.

![image](https://cloud.githubusercontent.com/assets/5070245/17502535/b9c3939e-5e23-11e6-986c-2787e07f8934.png)

해당 함수는 ratchet > common.js에 포함된 함수 입니다. 참고 부탁드립니다. 
https://github.com/twbs/ratchet/blob/master/js/common.js#L27

**Comment by kieregh** [comment]
우선 아래의 커밋 참조하시기 바랍니다.
https://github.com/kimsQ/rc/commit/13f74c0ed209be4b6fac52ce80a5e49202618f21

마크업 예제는 아래를 참조하시기 바랍니다.
http://www.withconsumer.net/rc-test/switch/default.html

이상입니다.

**Comment by gitaeks** [comment]
다른 폼관련 컴포넌트는 클릭환경에서도 작동되는 되요. `switch' 컴포넌트는 오직 터치환경에서만 작동되는 것 같습니다.  touch/click 두가지 환경을 지원하면 좋을 것 같습니다.

**Comment by gitaeks** [comment]
이벤트 명을 `rc.switched` 로 하신것을 `checked.rc.switch` 로 변경 하였습니다.
기존의 컴포넌트 이벤트의 네이밍 체계와 통일해야 할 필요성 때문 입니다.
아울러 `checked` 라는 용어를 선택한 것은 `switch`가 기능관점에서 `checkbox` 와 같기 때문입니다. 

---

![image](https://cloud.githubusercontent.com/assets/5070245/17835184/432fb3e0-679a-11e6-8a13-8372752c13b8.png)

---

### 참고

http://rc.kimsq.com/components/switch/#event

**Comment by kieregh** [comment]
우선...아래와 같이 click 이벤트 추가 적용 및 네이밍 관련 아래와 같이 커밋했습니다.
https://github.com/kimsQ/rc/commit/426d46783af48aee59859664c703472ee7b28825

##이벤트 네이밍 이슈 관련 제안
checked 는 On 상태를 의미하므로 반복되는 switch On/Off 이벤트 네이밍으로는 부적절한 것 같습니다.
그래서, 기존 rc 이벤트 네이밍 체계에도 부합되고 의미적으로도 매칭이 되도록 아래와 같이 제안합니다.
`changed.rc.switch`

참고로, bs switch 이벤트 네이밍 역시 changed 를 사용하고 있습니다.
http://www.bootstrap-switch.org/events.html

또한, 아래의 예제에서 switch 속성에 {cursor: pointer} 를 추가해서 데스크탑 환경을 고려했습니다.
http://www.withconsumer.net/rc-test/switch/default.html

이상입니다.

**Comment by gitaeks** [comment]
아래와 같이 처리했습니다.
https://github.com/kimsQ/rc/commit/53849f6781efdabb151dd387ae69e09bf0d2e108
