### ISSUE TITLE
브랜드 변경 ( Ratchet plus --> kimsQ RC )

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#36]
@kieregh ,  브랜드에 대해서 고민을 해왔는데요. kimsQ RC 로 통일하는게 효과적이겠다는 판단을 했습니다.
현재,  [공식 홈페이지](http://rc.kimsq.com/)에 변경해 놓았습니다.

파일명 또한 alpha2 릴리즈 때 아래와 같이 변경할 계획 입니다.
### Core
- rc.css
- rc.min.css
- rc.js
- rc.min.js
### Extra
- rc-progress.css
- rc-progress.min.css
### Extension
- rc-snap.js 
- rc-snap.css
- rc-swipe.js
- rc-photoswipe.js

**Comment by gitaeks** [comment]
@kieregh , 위와 같이 적용 완료했습니다. 참고해 주세요.

**Comment by kieregh** [comment]
네...인지했습니다.
