### ISSUE TITLE
Accordion(collapse) 적용 컴포넌트 추가 요청

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#37]
@kieregh , 현재 Accordion를 적용할 수 있는 컴포넌트는  `.card` 만 적용되어 있는데요. `.table-view` 도 추가요청 합니다. 
https://github.com/kimsQ/rc/blob/master/js/collapse.js#L52

**Comment by kieregh** [comment]
우선 아래의 커밋 참조하시기 바랍니다.
https://github.com/kimsQ/rc/commit/8291c14c4d6a6d25b19a89664260e7ef4e03f9f0

추가내용...
1. rc.kimsq.com 도큐먼트 마크업 수정해서 예제를 만들었습니다.
   http://www.withconsumer.net/rc-test/collapse/tree.html
   (parent 및 타겟 수정)
2. rc.kimsq.com 도큐먼트 > Accessibility 
   -  aria-expanded 값을 명시해주라고 되어 있는데 예제마크업에서는 적용되지 않는 것이 좀 그런것 같은데요....마크업을 심플하게 하기 위해서 그런거라면....Accessibility 부분을 언급하지 않는 방법도 있을 것 같습니다.
3. rc.kimsq.com 도큐먼트 > Options
   - parent 부분 설명에.....panel 부분을 삭제해야 할 것 같습니다.

이상입니다.

**Comment by gitaeks** [comment]
## rc.kimsq.com 도큐먼트 > Accessibility

접근성에 대한 고려로 마크업 복잡도가 증가하는것 같다는 의견을 주셔서 일단 제외하도록 하겠습니다. 
소스코드 예제 및 문서에서 `Accessibility` 에 대한 항목은 제거 했습니다.

## rc.kimsq.com 도큐먼트 > Options

제거 했습니다. 

수고하셨습니다.
