### ISSUE TITLE
Static Backdrop with Animation 관련

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#39]
@kieregh , Static Backdrop with Animation 기능이 이미 내장이 되어 있는 것 확인했습니다. 

아래 예제에 적용되어 있는데요.
http://rc.kimsq.com/examples/components/popup/static-backdrop-with-animation.html

아래 스크립트를 내장하는 방안을 요청 합니다.

```
      $('.backdrop').tap(function() {
        $("#myPopup .popup-content").addClass("animated shake");
        setTimeout(function() {
          $('#myPopup .popup-content').removeClass('animated shake');
        }, 600);
      });
```

`$('.backdrop').tap(function() {` 이부분이 작동하지 않는데요.  `.backdrop`에 `tap` 이벤트가 적용되지 않는 부분도 확인 요청 합니다.

**Comment by gitaeks** [comment]
관련 문서는 아래를 확인해 주세요. 
http://rc.kimsq.com/components/popup/#static-backdrop-with-animation

**Comment by gitaeks** [comment]
`data-backdrop="static"`  일 때는  오직 팝업 내부의 지정된 버튼을 통해서만 닫을수 있어야 할것 입니다.

아래의 2가지 경우에도 팝업을 닫을 수 없어야 할 것 같습니다.
- 백드롭 터치 --> animation(shake) 적용 
- 스마트폰 백버튼  --> 팝업출력시 히스토리를 적용하지 않음

**Comment by kieregh** [comment]
1. $('.backdrop').tap(function() ...관련 
   $('.backdrop').on('tap',function()...으로 수정하시기 바랍니다.
2. data-backdrop="static" ..관련...
   해당 데모 세스트한 결과 ....백드롭 클릭시 팝업이 닫히지 않고 잘 작동됩니다. 
   
   *\* 히스토리 관련 의견
   히스토리 옵션이 있는만큼 사용자가 원할 경우 히스토리를 false 로 설정하도록 안내하는 것이 맞다고 생각합니다. 

이상입니다.

**Comment by gitaeks** [comment]
shake 애니메이션을 적용하는 것은 어떻게 생각하세요 ?   backdrop tap 시에  흔들림 효과를 적용하려하는데요.

`.backdrop` 에는 어떤 이벤트도 먹지 않네요..

**Comment by gitaeks** [comment]
아래와 같이 테스트 중인데요.  작동을 안하네요. 

```
      $('.bakdrop').on('tap',function() {
        alert("111");
      });
```

**Comment by gitaeks** [comment]
아. 오타였습니다. 해결했습니다.

**Comment by gitaeks** [comment]
문서와 데모 모두 수정했습니다.
