### ISSUE TITLE
모달 URL 옵션 기본값

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#5]
@kieregh  현재,  모달의  `url` 옵션의 기본값이 없음으로 지정되어 있는데요.
### 문제점

그렇다보니, URL 옵션이 지정되지 않을 경우, 최종 파일명이 없어지는 현상이 있습니다.  최종파일명의 경로가 없는 URL이 공유될 경우, 외부접속시 없는 페이지로 유도될 가능성이 있습니다.
### 요청사항

`url`옵션의 기본값(미지정의 경우)을 현재 URL을 변경하지 않도록 처리하면 해결되지 않을까 합니다.

기본  false
### 예제

http://kimsq.github.io/rc/examples/component/modal/modal-option-title.html

**Comment by kieregh** [comment]
모달을 오픈했을 경우에 기존 부모 페이지 파일명이 사라지는 것이기 때문에 
궁극적으로 부모 페이지 최종페이지가 사라지는 것은 아니며...
오픈된 모달 페이지를 공유하고 외부접속을 고려한다면 당연히 url 를 설정해야 하는 것 아닌가요?

또한, 모달 오픈시 아무런 url 도 변경을 하지 않으면 back 버튼 이벤트시 문제가 발생합니다.

요컨대, 아래와 같이 기본 url 을 '##' 2 개로 변경했습니다.
테스트 결과 '#' 하나가 추가되고 사라지는 형태로 진행되기 때문에 외부접속 혹은 기능면에서도
문제가 없다고 생각합니다.
https://github.com/kimsQ/rc/commit/dd89fc64d82b1a06bcef83245118e5f01d662579

이상입니다.
