### ISSUE TITLE
popup 컨포넌트 backdrop 생성 위치 관련 요청

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#6]
@kieregh 님, 아래 popup 호출 데모에서 `<div class="backdrop"></div>`의 동적 생성 위치를 `</body>` 직전에 생성될수 있도록 수정 요청합니다.
### 데모

https://jsfiddle.net/gitaek/j2xyj6uc/

**Comment by kieregh** [comment]
data-container="body" 로 하면 됩니다.
기본값을 .content 에 생성하도록 했습니다.

**Comment by kieregh** [comment]
관련하여 아래와 같이 커밋했습니다.
https://github.com/kimsQ/rc/commit/f4dd6021a1d8ae746acadf6223324714f6a814b9
