### ISSUE TITLE
sheet,popover 컴포넌트 추가 요청

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#8]
@kieregh 님, popup 컨포넌트와 유사하게 sheet,popover 컨포넌트를 rc-component.js 에 각각 추가 요청합니다.

popup 클래스를 각각 sheet와 popover 로 치환 적용해 주면됩니다.

**Comment by kieregh** [comment]
popover 는 이미 되어 있는데요.....아래 샘플입니다.
http://www.withconsumer.net/rc-test/popover/static.html

sheet 마크업 샘플 주신다고 하셔서 대기하고 있습니다.

**Comment by gitaeks** [comment]
popover는 확인했습니다.  같은 방식으로 sheet도 추가 요청합니다.

**Comment by kieregh** [comment]
아래와 같이 sheet 추가했습니다.
https://github.com/kimsQ/rc/commit/f9ca6cf5ceff0377986ae6eaaac0a3fcbd4ec363

**Comment by gitaeks** [comment]
sheet에서  
`<div class="backdrop"></div>` 의 위치가 본문상에 표시 됩니다.   `</body>` 직전에 표시될수 있도록 해주세요.

**Comment by gitaeks** [comment]
popover에서 활성화시 적용되는 클래스를 아래와 같이 수정요청합니다. 
1. 활성 상태 클래스를 visible --> active 변경
2. rb-bottom 클래스 삭제
