### ISSUE TITLE
sheet 컴포넌트 오류

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rc#9]
@kieregh  아래의 데모에서 sheet호출시에 아래의 2가지 문제가 확인되었습니다. 
1.  `class="active"` 가 적용이 안되고  
2. `<div class="backdrop"></div>` 이 `</body>` 직전에 생성이 안됨. 
#### 데모

https://jsfiddle.net/gitaek/4og88s6s/

**Comment by kieregh** [comment]
아래 2 개의 커밋으로 해결되었습니다. 
https://github.com/kimsQ/rc/commit/4cb0ad9365d9c01e9007212d5efbe9db8173738a
https://github.com/kimsQ/rc/commit/8a09aa5e146f2e07c9c6fe81549306b7c4a71b8b

**Comment by gitaeks** [comment]
아래 링크방식에서 안되는데요. 확인해주세요. 

https://jsfiddle.net/gitaek/2ta3k7t9/

**Comment by gitaeks** [comment]
해결했습니다. sheet 내부 마크업과 CSS 이슈였습니다.
